version: '3.8'

services:
  regression:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    working_dir: /usr/workspace
    command: >
      sh -c "pytest -sv --alluredir=allure-results
      && allure generate allure-results --clean -o allure-report
      || echo 'Test execution completed'"