version: '3.8'

services:
  regression:
    build:
      context: .
      dockerfile: Dockerfile
    user: "${UID:-1000}:${GID:-1000}"  # Используем UID/GID хоста
    volumes:
      - ./allure-results:/usr/workspace/allure-results
      - ./allure-report:/usr/workspace/allure-report
      - ./pytest.ini:/usr/workspace/pytest.ini  # только конфиги
      - ./tests:/usr/workspace/tests  # только тесты
    working_dir: /usr/workspace
    environment:
      - ALLURE_NO_ANALYTICS=1
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "pytest -sv --alluredir=allure-results
      && allure generate allure-results --clean -o allure-report --no-perms
      || echo 'Test execution completed with status $?'"