version: '3.8'

services:
  regression:
    build: .
    volumes:
      - ./:/usr/workspace
      - ./allure-results:/usr/workspace/allure-results
      - ./allure-report:/usr/workspace/allure-report
    working_dir: /usr/workspace
    command: >
      sh -c "pytest tests/ --alluredir=allure-results;
             allure generate allure-results --clean -o allure-report"